global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Nginx Load Balancer metrics
  - job_name: 'nginx-load-balancer'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 5s
    metrics_path: /metrics

  # Web1 server metrics
  - job_name: 'web1-server'
    static_configs:
      - targets: ['web1-exporter:9113']
    scrape_interval: 5s
    metrics_path: /metrics

  # Web2 server metrics
  - job_name: 'web2-server'
    static_configs:
      - targets: ['web2-exporter:9113']
    scrape_interval: 5s
    metrics_path: /metrics

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']